routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes(['register'=>false]);
Route::middleware(['auth'])->group(function () {
    Route::post('/', 'RoleController@permissionGrant')->name('permissions.grant');
    Route::get('/', 'HomeController@index')->name('home');
    Route::delete('shortcodes/{id}', 'ClientController@deleteShortCode')->name('shortcodes.delete');
    Route::get('/home', 'HomeController@index')->name('home');
    Route::post('/clients/add_code', 'ClientController@addShortCode')->name('clients.add_code');
    Route::get('/clients/short_codes/{id}', 'ClientController@getShortCodes')->name('clients.getShortCodes');
    Route::resource('/clients', 'ClientController');
    Route::resource('/users', 'UserController');
    Route::resource('/short_codes', 'ShortCodeController');
    Route::resource('/roles', 'RoleController');
    Route::resource('/system_configs', 'SystemConfigController');
    Route::get('/blasts/execute/{id}', 'BlastController@execute')->name('blast.execute');
    Route::get('/shortcode/change/{id}', 'ShortCodeController@change')->name('shortcode.change');
    Route::post('/blasts/upload', 'BlastController@upload')->name("blast.upload");
    Route::post('/blasts/template', 'BlastController@template')->name("blast.template");
    Route::resource('/blasts', 'BlastController');
    Route::get('/billing/usage', 'BillingController@usage')->name('billing.usage');
    Route::resource('/billing', 'BillingController');
    Route::get('/billing/{id}/{action}', 'BillingController@action')->name('billing.action');
    Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index')->name('logs');
    Route::get('/reports/messages', 'ReportController@messagesReport')->name('reports.messages');
    Route::get('/reports/messages_ajax', 'ReportController@messagesAjax')->name('reports.messages_ajax');
    Route::get('/reports/messages_data', 'ReportController@messagesData')->name('reports.messages.data');
    Route::get('/template/{id}/{action}', 'TemplateController@action')->name('template.action');
    Route::resource('/templates', 'TemplateController');
    Route::resource('/templates_uploads', 'TemplateUploadController');
    Route::get('/audit', 'ReportController@auditReport')->name('reports.audit');
    Route::get('/templates_uploads/approve/{id}', 'TemplateUploadController@approve')->name('template_uploads.approve');
    Route::get('/templates_uploads/report/{id}', 'TemplateUploadController@report')->name('template_uploads.report');
});

app/User.php
<?php

namespace App;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Http\Request;
use Illuminate\Notifications\Notifiable;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Log;
use Instasent\SMSCounter\SMSCounter;
use Laravel\Passport\HasApiTokens;
use Spatie\Permission\Traits\HasRoles;

class User extends Authenticatable
{
    use Notifiable;
    use HasRoles;
    use HasApiTokens;
    use SoftDeletes;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'phone_number', 'alert_threshold', 'available_units'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];


    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        self::created(function ($record) {
            Audit::log(Request::capture(), 'CREATE_USER', "Created user id $record->id");
        });
        self::updated(function ($record) {
            Audit::log(Request::capture(), 'UPDATE_USER', "Updated user id $record->id");
        });
        self::deleted(function ($record) {
            Audit::log(Request::capture(), 'DELETE_USER', "Deleted user id $record->id");
        });
    }

    public function getRoleAttribute()
    {
        $roles = $this->getRoleNames();
        return count($roles) > 0 ? $roles[0] : 'None';
    }

    public function getRoleObjAttribute()
    {
        $roles = Auth::user()->roles();
        return $roles->count() > 0 ? $roles->first() : null;
    }

    public function getLinkAttribute()
    {
        return link_to(route('users.show', [$this->id]), $this->name);
    }

    public function getFirstNameAttribute()
    {
        return explode(" ", $this->name)[0];
    }

    public function getIsMeAttribute()
    {
        return Auth::user()->id == $this->id;
    }

    /**
     * @return array
     */
    public function getAvailableUnitsAttributes()
    {
        return $this->available_units;
    }

    public function getLastNameAttribute()
    {
        $nameArray = explode(" ", $this->name);
        return count($nameArray) > 1 ? $nameArray[1] : "";
    }

    public function charge($units)
    {
        $user = User::where("id", $this->id)->lockForUpdate()->first();
        $initialBal = $user->available_units;
        $user->available_units = ($currentBal = $user->available_units - $units);
        $user->save();

        if ($initialBal >= $user->alert_threshold && $currentBal < $user->alert_threshold
            && !is_null($user->phone_number) && strlen($user->phone_number) >= 9) {
            Log::info("Sending usage alert to $user->phone_number");
            //Send alert message


            $smsCounter = new SMSCounter();
            $segments = $smsCounter->count($message = $smsCounter->sanitizeToGSM("Your current balance of $user->available_units  is below $user->alert_threshold. Kindly top up to avoid service disruption"))->messages;

            $blast = Message::updateOrCreate(
                [
                    'tracker_id' => uniqid('', true),
                ],
                [
                    'sender_id' => SystemShortCode::all()->first()->short_code,
                    'message' => $message,
                    'message_ref' => uniqid('', true),
                    'phone_number' => "254" . substr($user->phone_number, -9),
                    'dlr_callback_url' => "",
                    'segments' => $segments,
                    'scheduled_at' => Carbon::now()
                ]);
//            ProcessBlast::dispatch($blast)->delay($blast->scheduled_at);
        }
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use Spatie\Permission\Models\Role;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $page_name = 'Users';
        $users = User::withTrashed()
            ->orderBy("created_at", 'DESC')
            ->paginate(10);
        $roles = Role::all();
        return view('users.index', compact('users', 'page_name', 'roles'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\RedirectResponse
     * @throws \Illuminate\Validation\ValidationException
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'first_name' => 'required',
            'last_name' => 'required',
            'email' => 'required|unique:users',
            'phone_number' => 'required|unique:users',
            'role' => 'required|exists:roles,id',
            'password' => 'min:8|regex:/[a-z]/|regex:/[A-Z]/|regex:/[0-9]/|regex:/[@$!%*#?&]/',
        ]);
        $user = User::updateOrCreate(
            [
                'email' => $request->email
            ],
            [
                'phone_number' => $request->phone_number,
                'name' => $request->first_name . " " . $request->last_name,
                'password' => Hash::make($request->password)
            ]
        );

        $role = Role::find($request->role);
        $user->assignRole($role);
        $request->session()->flash('success', 'User account created');
        return back();
    }

    /**
     * Display the specified resource.
     *
     * @param \App\User $user
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
        $page_name = $user->name . ' Profile';
        $roles = Role::all();
        return view('users.show', compact('user', 'page_name', 'roles'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param \App\User $system
     * @return \Illuminate\Http\Response
     */
    public function edit(User $system)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param User $user
     * @return \Illuminate\Http\RedirectResponse
     * @throws \Illuminate\Validation\ValidationException
     */
    public function update(Request $request, User $user)
    {
        $this->validate($request, [
            'first_name' => 'required',
            'last_name' => 'required',
            'email' => 'required',
            'role' => 'required|exists:roles,id',
            'password' => 'nullable|min:8|regex:/[a-z]/|regex:/[A-Z]/|regex:/[0-9]/|regex:/[@$!%*#?&]/',
        ]);
        $user = User::updateOrCreate(
            [
                'id' => $user->id
            ],
            [
                'email' => $request->email,
                'phone_number' => $request->phone_number,
                'alert_threshold' => $request->alert_threshold,
                'name' => $request->first_name . " " . $request->last_name,
//                'password' => Hash::make($request->password)
            ]
        );
        if (isset($request->password) && $request->password != '')
            $user = User::updateOrCreate(
                [
                    'id' => $user->id
                ],
                [
                    'password' => Hash::make($request->password)
                ]
            );

        $user->removeRole($user->role);
        $role = Role::find($request->role);
        $user->assignRole($role);
        $request->session()->flash('success', 'User account updated');
        return back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Request $request
     * @param User $user
     * @return \Illuminate\Http\RedirectResponse
     * @throws \Exception
     */
    public function destroy(Request $request, $userId)
    {
        $user = User::withTrashed()->where("id", $userId)->first();
        if ($user->trashed()) {
            $request->session()->flash('success', 'User account restored');
            $user->restore();
        } else {
            $user->delete();
            $request->session()->flash('success', 'User account deleted');
        }
        return back();
    }
}

resources/views/users/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    @can('Create users')
                        <button data-toggle="modal" class=" btn btn-sm btn-danger pull-right"
                                data-target=".bs-example-modal-lg">Create user
                        </button>
                    @endcan
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">
                    <div class="table-responsive">
                        <table class="table table-striped table-sm">
                            <thead>
                            <tr>
                                <th>#</th>
                                <th>Name</th>
                                <th>Phone Number</th>
                                <th>Email</th>
                                <th>Role</th>
                                <th>Units Balance</th>
                                <th>Alert Threshold</th>
                                <th>Last connected</th>
                                <th></th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($users as $user)
                                <tr>
                                    <td>{{ $user->id }}</td>
                                    <td>{{ $user->link }}</td>
                                    <td>{{ $user->phone_number }}</td>
                                    <td>{{ $user->email }}</td>
                                    <td>{{ $user->role }}</td>
                                    <td>{{ $user->available_units }}</td>
                                    <td>{{ $user->alert_threshold }}</td>
                                    <td>{{ $user->updated_at->diffForHumans() }}</td>
                                    <td>
                                        @can('Delete users')
                                            {{ Form::model($user,['url' => '/users/'.$user->id,'method' => 'DELETE']) }}
                                            <input type="hidden" name="id" value="{{ $user->id}}"/>
                                            <button type="submit"
                                                    class="btn {{$user->trashed() ? 'btn-info':'btn-danger'}}  btn-xs"> {{$user->trashed() ? 'Restore':'Delete'}}</button>
                                            {{ Form::close() }}
                                        @endcan
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                        {{ $users->links() }}
                    </div>
                </div>
            </div>
        </div>
    </div>
@stop

@section('modals')
    @can('Create users')
        <div class="modal fade bs-example-modal-lg" tabindex="-1" role="dialog" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span>
                        </button>
                        <h4 class="modal-title" id="myModalLabel">Create user</h4>
                    </div>
                    {{ Form::open(['route' => 'users.store']) }}
                    <div class="modal-body">
                        <div class="form-group row">
                            <div class="col-sm-6">
                                <label>First Name<span class="required">*</span></label>
                                {{  Form::text('first_name', $value = null, $attributes =[
                                'class' => 'form-control'
                                ]) }}
                            </div>
                            <div class="col-sm-6">
                                <label>Last Name<span class="required">*</span></label>
                                {{  Form::text('last_name', $value = null, $attributes =[
                                'class' => 'form-control'
                                ]) }}
                            </div>
                        </div>
                        <div class="form-group">
                            <label>Role<span class="required">*</span></label>
                            <select class="form-control" name="role">
                                @foreach($roles as $role)
                                    <option value="{{ $role->id }}">{{ $role->name }}</option>
                                @endforeach
                            </select>
                        </div>
                        <div class="form-group">
                            <label>Email address<span class="required">*</span></label>
                            {{  Form::email('email', $value = null, $attributes =[
                            'class' => 'form-control'
                            ]) }}
                        </div>
                        <div class="form-group">
                            <label>Phone Number<span class="required">*</span></label>
                            {{  Form::text('phone_number', $value = null, $attributes =['class' => 'form-control']) }}
                        </div>
                        <div class="form-group">
                            <label>Set Password<span class="required">*</span></label>
                            {{  Form::password( $value = null, $attributes =['name'=>'password',
                            'class' => 'form-control'
                            ]) }}
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-primary">Create User</button>
                    </div>
                    {{ Form::close() }}
                </div>
            </div>
        </div>
    @endcan
@stop

resources/views/users/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <h2>{{ $user->name }}
                        <small>Profile details</small>
                    </h2>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">
                    <div class="col-md-3 col-sm-3 col-xs-12 profile_left">
                        <h3>{{ $user->name }}</h3>
                        <ul class="list-unstyled user_data">
                            <li><i class="fa fa-envelope user-profile-icon"></i>
                                {{ $user->email }}
                            </li>
                            <li>
                                <i class="fa fa-briefcase user-profile-icon"></i> {{$user->role}}
                            </li>
                        </ul>
                        @if(Gate::check('Edit users') || $user->is_me)
                            <a class="btn btn-success" data-toggle="modal" data-target=".bs-example-modal-lg"><i
                                    class="fa fa-edit m-right-xs"></i>Edit Profile</a>
                        @endif
                        <br/>
                    </div>
                    <div class="col-md-9 col-sm-9 col-xs-12">
                        <div class="" role="tabpanel" data-example-id="togglable-tabs">
                            <ul id="myTab" class="nav nav-tabs bar_tabs" role="tablist">
                                <li role="presentation" class="active">
                                    <a href="#tab_content1" id="home-tab" role="tab" data-toggle="tab"
                                       aria-expanded="true">Recent activities</a>
                                </li>
                                <li role="presentation" class="">
                                    <a href="#tab_content2" role="tab" id="profile-tab"
                                       data-toggle="tab" aria-expanded="false">Projects</a>
                                </li>
                            </ul>
                            <div id="myTabContent" class="tab-content">
                                <div role="tabpanel" class="tab-pane fade active in" id="tab_content1"
                                     aria-labelledby="home-tab">
                                </div>
                                <div role="tabpanel" class="tab-pane fade" id="tab_content2"
                                     aria-labelledby="profile-tab">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@stop

@section('modals')
    @can('Edit users')
        <div class="modal fade bs-example-modal-lg" tabindex="-1" role="dialog" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span>
                        </button>
                        <h4 class="modal-title" id="myModalLabel">Edit {{ $user->name }}</h4>
                    </div>
                    {{ Form::model($user,['route' => ['users.update', $user->id],'method' => 'put']) }}

                    <div class="modal-body">
                        <div class="form-group row">
                            <div class="col-sm-6">
                                <label>First Name<span class="required">*</span></label>
                                {{  Form::text('first_name', $value = $user->first_name, $attributes =[
                                'class' => 'form-control'
                                ]) }}
                            </div>
                            <div class="col-sm-6">
                                <label>Last Name<span class="required">*</span></label>
                                {{  Form::text('last_name', $value = $user->last_name, $attributes =[
                                'class' => 'form-control'
                                ]) }}
                            </div>
                        </div>

                        <div class="form-group">
                            <label>Role<span class="required">*</span></label>
                            <select class="form-control" name="role">
                                @foreach($roles as $role)
                                    <option
                                        {{ $user->role == $role->name ? 'selected':'' }} value="{{ $role->id }}">{{ $role->name }}</option>
                                @endforeach
                            </select>
                        </div>
                        <div class="form-group">
                            <label>Email address<span class="required">*</span></label>
                            {{  Form::email('email', $value = $user->email, $attributes =[
                            'class' => 'form-control'
                            ]) }}
                        </div>
                        <div class="form-group">
                            <label>Phone Number<span class="required">*</span></label>
                            {{  Form::text('phone_number', $value = $user->phone_number, $attributes =[
                            'class' => 'form-control'
                            ]) }}
                        </div>
                        <div class="form-group">
                            <label>Usage alert threshold<span class="required">*</span></label>
                            {{  Form::text('alert_threshold', $value = $user->alert_threshold, $attributes =['class' => 'form-control']) }}
                        </div>
                        @can('Reset user password')
                            @if(!$user->is_me)
                                <div class="form-group">
                                    <label>Set New Password<span class="required">*</span></label>
                                    {{  Form::password( $value = null, $attributes =['name'=>'password',
                                    'class' => 'form-control'
                                    ]) }}
                                </div>
                            @endif
                        @endcan
                        @if($user->is_me)
                            <div class="form-group">
                                <label>Reset Password<span class="required">*</span></label>
                                {{  Form::password( $value = null, $attributes =['name'=>'password',
                                'class' => 'form-control'
                                ]) }}
                            </div>
                        @endif
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-primary">Update</button>
                    </div>
                    {{ Form::close() }}
                </div>
            </div>
        </div>
    @endcan
@stop

@section('styles')
    <link href="{{ asset('vendors/bootstrap-daterangepicker/daterangepicker.css') }}" rel="stylesheet">
@stop
@section('scripts')
    <script src="{{ asset('/vendors/raphael/raphael.min.js') }}"></script>
    <script src="{{ asset('/vendors/morris.js/morris.min.js') }}"></script>
    <!-- bootstrap-progressbar -->
    <script src="{{ asset('/vendors/bootstrap-progressbar/bootstrap-progressbar.min.js') }}"></script>
    <!-- bootstrap-daterangepicker -->
    <script src="{{ asset('/vendors/moment/min/moment.min.js') }}"></script>
    <script src="{{ '/vendors/bootstrap-daterangepicker/daterangepicker.js' }}"></script>

@stop