routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes(['register'=>false]);
Route::middleware(['auth'])->group(function () {
    Route::post('/', 'RoleController@permissionGrant')->name('permissions.grant');
    Route::get('/', 'HomeController@index')->name('home');
    Route::delete('shortcodes/{id}', 'ClientController@deleteShortCode')->name('shortcodes.delete');
    Route::get('/home', 'HomeController@index')->name('home');
    Route::post('/clients/add_code', 'ClientController@addShortCode')->name('clients.add_code');
    Route::get('/clients/short_codes/{id}', 'ClientController@getShortCodes')->name('clients.getShortCodes');
    Route::resource('/clients', 'ClientController');
    Route::resource('/users', 'UserController');
    Route::resource('/short_codes', 'ShortCodeController');
    Route::resource('/roles', 'RoleController');
    Route::resource('/system_configs', 'SystemConfigController');
    Route::get('/blasts/execute/{id}', 'BlastController@execute')->name('blast.execute');
    Route::get('/shortcode/change/{id}', 'ShortCodeController@change')->name('shortcode.change');
    Route::post('/blasts/upload', 'BlastController@upload')->name("blast.upload");
    Route::post('/blasts/template', 'BlastController@template')->name("blast.template");
    Route::resource('/blasts', 'BlastController');
    Route::get('/billing/usage', 'BillingController@usage')->name('billing.usage');
    Route::resource('/billing', 'BillingController');
    Route::get('/billing/{id}/{action}', 'BillingController@action')->name('billing.action');
    Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index')->name('logs');
    Route::get('/reports/messages', 'ReportController@messagesReport')->name('reports.messages');
    Route::get('/reports/messages_ajax', 'ReportController@messagesAjax')->name('reports.messages_ajax');
    Route::get('/reports/messages_data', 'ReportController@messagesData')->name('reports.messages.data');
    Route::get('/template/{id}/{action}', 'TemplateController@action')->name('template.action');
    Route::resource('/templates', 'TemplateController');
    Route::resource('/templates_uploads', 'TemplateUploadController');
    Route::get('/audit', 'ReportController@auditReport')->name('reports.audit');
    Route::get('/templates_uploads/approve/{id}', 'TemplateUploadController@approve')->name('template_uploads.approve');
    Route::get('/templates_uploads/report/{id}', 'TemplateUploadController@report')->name('template_uploads.report');
});

app/TemplateUploadMessage.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class TemplateUploadMessage extends Model
{
    use SoftDeletes;

    protected $fillable = ['template_upload_id', 'phone_number', 'message', 'processed'];

    public function sentMessage()
    {
        return $this->belongsTo(Message::class,'message_id');
    }


    public function getStatusAttribute()
    {
        return $this->processed ? 'Processed':'Pending';
    }
}

app/User.php
<?php

namespace App;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Http\Request;
use Illuminate\Notifications\Notifiable;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Log;
use Instasent\SMSCounter\SMSCounter;
use Laravel\Passport\HasApiTokens;
use Spatie\Permission\Traits\HasRoles;

class User extends Authenticatable
{
    use Notifiable;
    use HasRoles;
    use HasApiTokens;
    use SoftDeletes;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'phone_number', 'alert_threshold', 'available_units'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];


    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        self::created(function ($record) {
            Audit::log(Request::capture(), 'CREATE_USER', "Created user id $record->id");
        });
        self::updated(function ($record) {
            Audit::log(Request::capture(), 'UPDATE_USER', "Updated user id $record->id");
        });
        self::deleted(function ($record) {
            Audit::log(Request::capture(), 'DELETE_USER', "Deleted user id $record->id");
        });
    }

    public function getRoleAttribute()
    {
        $roles = $this->getRoleNames();
        return count($roles) > 0 ? $roles[0] : 'None';
    }

    public function getRoleObjAttribute()
    {
        $roles = Auth::user()->roles();
        return $roles->count() > 0 ? $roles->first() : null;
    }

    public function getLinkAttribute()
    {
        return link_to(route('users.show', [$this->id]), $this->name);
    }

    public function getFirstNameAttribute()
    {
        return explode(" ", $this->name)[0];
    }

    public function getIsMeAttribute()
    {
        return Auth::user()->id == $this->id;
    }

    /**
     * @return array
     */
    public function getAvailableUnitsAttributes()
    {
        return $this->available_units;
    }

    public function getLastNameAttribute()
    {
        $nameArray = explode(" ", $this->name);
        return count($nameArray) > 1 ? $nameArray[1] : "";
    }

    public function charge($units)
    {
        $user = User::where("id", $this->id)->lockForUpdate()->first();
        $initialBal = $user->available_units;
        $user->available_units = ($currentBal = $user->available_units - $units);
        $user->save();

        if ($initialBal >= $user->alert_threshold && $currentBal < $user->alert_threshold
            && !is_null($user->phone_number) && strlen($user->phone_number) >= 9) {
            Log::info("Sending usage alert to $user->phone_number");
            //Send alert message


            $smsCounter = new SMSCounter();
            $segments = $smsCounter->count($message = $smsCounter->sanitizeToGSM("Your current balance of $user->available_units  is below $user->alert_threshold. Kindly top up to avoid service disruption"))->messages;

            $blast = Message::updateOrCreate(
                [
                    'tracker_id' => uniqid('', true),
                ],
                [
                    'sender_id' => SystemShortCode::all()->first()->short_code,
                    'message' => $message,
                    'message_ref' => uniqid('', true),
                    'phone_number' => "254" . substr($user->phone_number, -9),
                    'dlr_callback_url' => "",
                    'segments' => $segments,
                    'scheduled_at' => Carbon::now()
                ]);
//            ProcessBlast::dispatch($blast)->delay($blast->scheduled_at);
        }
    }
}

app/Http/Controllers/ShortCodeController.php
<?php

namespace App\Http\Controllers;

use App\Audit;
use App\Message;
use App\ShortCode;
use App\SystemShortCode;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Spatie\Permission\Models\Role;

class ShortCodeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $page_name = 'Short Codes';
        $shortCodes = SystemShortCode::paginate(10);
        $roles = Role::all();
        return view('shortcodes.index', compact('shortCodes', 'page_name', 'roles'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\RedirectResponse
     * @throws \Illuminate\Validation\ValidationException
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'short_code' => 'required'
        ]);
        $user = SystemShortCode::updateOrCreate(
            [
                'short_code' => $request->email
            ],
            [
                'description' => $request->description
            ]
        );


        $request->session()->flash('success', 'Short code registered successfully');
        return back();
    }

    /**
     * Display the specified resource.
     *
     * @param \App\User $shortCode
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Http\Response|\Illuminate\View\View
     */
    public function show(SystemShortCode $shortCode)
    {
        $page_name = $shortCode->short_code . ' Profile';
        $blasts = Message::select("*")
            ->where('sender_id', $shortCode->short_code)
            ->orderBy("created_at", "DESC")
            ->distinct()
            ->paginate(10);

        $roles = DB::table('roles')->select('roles.*', 'scr.status', 'scr.id as scr_id')
            ->join('short_code_roles as scr', 'scr.role_id', 'roles.id')
            ->where("system_shortcode_id", $shortCode->id)
            ->paginate(10);

        return view('shortcodes.show', compact('shortCode', 'page_name', 'roles', 'blasts'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param \App\User $system
     * @return \Illuminate\Http\Response
     */
    public function edit(User $system)
    {
        //
    }

    public function change(Request $request, $id)
    {
        $record = DB::table('short_code_roles')->where("id", $id)->first();
        if (!is_null($record)) {
            DB::update('UPDATE short_code_roles set status =? where id = ?', [$status = ($record->status === 'ACTIVE' ? 'NOT ACTIVE' : 'ACTIVE'), $id]);
        }
        Audit::log($request, 'ASSIGN_SHORTCODE', "Changed shortcode id $record->system_shortcode_id role id $record->role_id assignment to $status ");
        $request->session()->flash('success', 'Short code assignment status changed');
        return back();
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param User $user
     * @return \Illuminate\Http\Response
     * @throws \Illuminate\Validation\ValidationException
     */
    public function update(Request $request, User $user)
    {
        $this->validate($request, [
            'first_name' => 'required',
            'last_name' => 'required',
            'email' => 'required',
            'role' => 'required|exists:roles,id',
            'password' => 'nullable|min:8|regex:/[a-z]/|regex:/[A-Z]/|regex:/[0-9]/|regex:/[@$!%*#?&]/',
        ]);
        $user = User::updateOrCreate(
            [
                'id' => $user->id
            ],
            [
                'email' => $request->email,
                'phone_number' => $request->phone_number,
                'alert_threshold' => $request->alert_threshold,
                'name' => $request->first_name . " " . $request->last_name,
//                'password' => Hash::make($request->password)
            ]
        );

        $user->removeRole($user->role);

        $role = Role::find($request->role);
        $user->assignRole($role);
        $request->session()->flash('success', 'User account updated');
        return back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Request $request
     * @param User $user
     * @return void
     * @throws \Exception
     */
    public function destroy(Request $request, User $user)
    {
        $user->delete();
        $request->session()->flash('success', 'User account deleted');
        return back();
    }
}

resources/views/shortcodes/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    @can('Create sender ids')
                        <button data-toggle="modal" class=" btn btn-sm btn-danger pull-right"
                                data-target=".add_shortcode">Add Short Code
                        </button>
                    @endcan
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">
                    <div class="table-responsive">
                        <table class="table table-striped table-sm">
                            <thead>
                            <tr>
                                <th>#</th>
                                <th>Short Code</th>
                                <th>Created on</th>
                                <th>Description</th>
                                <th></th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($shortCodes as $record)
                                <tr>
                                    <td>{{ $record->id }}</td>
                                    <td>{{ $record->link }}</td>
                                    <td>{{ $record->created_at }}</td>
                                    <td>{{ $record->description }}</td>
                                    <td></td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                        {{ $shortCodes->links() }}
                    </div>
                </div>
            </div>
        </div>
    </div>
@stop



@section('modals')
    @can('Create sender ids')
        <div class="modal fade add_shortcode" tabindex="-1" role="dialog" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">

                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span>
                        </button>
                        <h4 class="modal-title" id="myModalLabel">Add short code</h4>
                    </div>
                    {{ Form::open(['route' => 'clients.add_code']) }}
                    <div class="modal-body">
{{--                        <input type="hidden" name="client" value="{{ $client->id }}"/>--}}
                        <div class="form-group">
                            <label>Short code</label>
                            <input type="text" name="short_code" class="form-control"/>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-primary">Map short code</button>
                    </div>
                    {{ Form::close() }}
                </div>
            </div>
        </div>
    @endcan
@stop

resources/views/shortcodes/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <h2>{{ $shortCode->short_code }}
                        <small>Profile details</small>
                    </h2>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">
                    <div class=" col-xs-12">
                        <div class="" role="tabpanel" data-example-id="togglable-tabs">
                            <ul id="myTab" class="nav nav-tabs bar_tabs" role="tablist">
                                <li role="presentation" class="active">
                                    <a href="#tab_content1" id="home-tab" role="tab" data-toggle="tab"
                                       aria-expanded="true">Messages</a>
                                </li>
                                <li role="presentation" class="">
                                    <a href="#tab_content2" role="tab" id="profile-tab"
                                       data-toggle="tab" aria-expanded="false">Assigned Roles</a>
                                </li>
                            </ul>
                            <div id="myTabContent" class="tab-content">
                                <div role="tabpanel" class="tab-pane fade active in" id="tab_content1"
                                     aria-labelledby="home-tab">

                                    <table class="table table-striped table-sm  no-margin">
                                        <thead>
                                        <tr>
                                            <th>Id</th>
                                            <th>Phone number</th>
                                            <th>Message</th>
                                            <th>Status</th>
                                            <th>Delivery Status</th>
                                            <th>Created at</th>
                                            <th>Sent at</th>
                                            <th>Submit Date</th>
                                            <th>Done Date</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        @foreach($blasts as $blast)
                                            <tr>
                                                <td>{{ $blast->id }}</td>
                                                <td>{{ $blast->phone_number }}</td>
                                                <td>{{ $blast->message }}</td>
                                                <td>{{ $blast->status }}</td>
                                                <td>{{ $blast->delivery_status }}</td>
                                                <td>{{ $blast->scheduled_at }}</td>
                                                <td>{{ ($blast->processed_at) }}</td>
                                                <td>{{ ($blast->submit_date) }}</td>
                                                <td>{{ ($blast->done_date) }}</td>
                                            </tr>
                                        @endforeach
                                        </tbody>
                                    </table>
                                    {{ $blasts->links() }}

                                </div>
                                <div role="tabpanel" class="tab-pane fade" id="tab_content2"
                                     aria-labelledby="profile-tab">


                                    <table class="table table-striped table-sm  no-margin">
                                        <thead>
                                        <tr>
                                            <th>Id</th>
                                            <th>Name</th>
                                            <th>Status</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        @foreach($roles as $role)
                                            <tr>
                                                <td>{{ $role->id }}</td>
                                                <td><a href="{{ route('roles.show', $role->id) }}">{{ $role->name }}</a>
                                                </td>
                                                <td>{{ $role->status }}</td>
                                                <td>
                                                    <a href="{{ route('shortcode.change', $role->scr_id) }}"
                                                       class=" btn btn-sm btn-danger pull-right">Change
                                                    </a>
                                                </td>
                                            </tr>
                                        @endforeach
                                        </tbody>
                                    </table>
                                    {{ $roles->links() }}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@stop


@section('styles')
    <link href="{{ asset('vendors/bootstrap-daterangepicker/daterangepicker.css') }}" rel="stylesheet">
@stop
@section('scripts')
    <script src="{{ asset('/vendors/raphael/raphael.min.js') }}"></script>
    <script src="{{ asset('/vendors/morris.js/morris.min.js') }}"></script>
    <!-- bootstrap-progressbar -->
    <script src="{{ asset('/vendors/bootstrap-progressbar/bootstrap-progressbar.min.js') }}"></script>
    <!-- bootstrap-daterangepicker -->
    <script src="{{ asset('/vendors/moment/min/moment.min.js') }}"></script>
    <script src="{{ '/vendors/bootstrap-daterangepicker/daterangepicker.js' }}"></script>

@stop