routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes(['register'=>false]);
Route::middleware(['auth'])->group(function () {
    Route::post('/', 'RoleController@permissionGrant')->name('permissions.grant');
    Route::get('/', 'HomeController@index')->name('home');
    Route::delete('shortcodes/{id}', 'ClientController@deleteShortCode')->name('shortcodes.delete');
    Route::get('/home', 'HomeController@index')->name('home');
    Route::post('/clients/add_code', 'ClientController@addShortCode')->name('clients.add_code');
    Route::get('/clients/short_codes/{id}', 'ClientController@getShortCodes')->name('clients.getShortCodes');
    Route::resource('/clients', 'ClientController');
    Route::resource('/users', 'UserController');
    Route::resource('/short_codes', 'ShortCodeController');
    Route::resource('/roles', 'RoleController');
    Route::resource('/system_configs', 'SystemConfigController');
    Route::get('/blasts/execute/{id}', 'BlastController@execute')->name('blast.execute');
    Route::get('/shortcode/change/{id}', 'ShortCodeController@change')->name('shortcode.change');
    Route::post('/blasts/upload', 'BlastController@upload')->name("blast.upload");
    Route::post('/blasts/template', 'BlastController@template')->name("blast.template");
    Route::resource('/blasts', 'BlastController');
    Route::get('/billing/usage', 'BillingController@usage')->name('billing.usage');
    Route::resource('/billing', 'BillingController');
    Route::get('/billing/{id}/{action}', 'BillingController@action')->name('billing.action');
    Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index')->name('logs');
    Route::get('/reports/messages', 'ReportController@messagesReport')->name('reports.messages');
    Route::get('/reports/messages_ajax', 'ReportController@messagesAjax')->name('reports.messages_ajax');
    Route::get('/reports/messages_data', 'ReportController@messagesData')->name('reports.messages.data');
    Route::get('/template/{id}/{action}', 'TemplateController@action')->name('template.action');
    Route::resource('/templates', 'TemplateController');
    Route::resource('/templates_uploads', 'TemplateUploadController');
    Route::get('/audit', 'ReportController@auditReport')->name('reports.audit');
    Route::get('/templates_uploads/approve/{id}', 'TemplateUploadController@approve')->name('template_uploads.approve');
    Route::get('/templates_uploads/report/{id}', 'TemplateUploadController@report')->name('template_uploads.report');
});

app/TemplateUploadMessage.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class TemplateUploadMessage extends Model
{
    use SoftDeletes;

    protected $fillable = ['template_upload_id', 'phone_number', 'message', 'processed'];

    public function sentMessage()
    {
        return $this->belongsTo(Message::class,'message_id');
    }


    public function getStatusAttribute()
    {
        return $this->processed ? 'Processed':'Pending';
    }
}

resources/views/templates/index.blade.php
@extends('layouts.app')

@section('scripts')
    <script>
        $(document).ready(function () {
            $(".delete-template").on('click', function () {
                var r = confirm("Are you sure you want to delete this message template?");
                if (r) {
                    $.ajax({
                        url: '{{ url('templates') }}/' + $(this).attr('id'),
                        type: 'DELETE',  // user.destroy
                        success: function (result) {
                            console.log(result);
                            location.reload();
                        },
                        fail: function (error) {
                            console.log(error);
                            alert("Error deleting template");
                        }
                    });
                }
            });
        });
    </script>
@endsection
@section('actions')
    <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
        <form method="get">
            <div class="input-group">
                <input type="text" name="search" value="{{ isset($_GET['search']) ? Request::get('search') :'' }}"
                       class="form-control"
                       placeholder="Search for...">
                <span class="input-group-btn"><button class="btn btn-default" type="submit">Search</button></span>
            </div>
        </form>
    </div>
@endsection
@section('content')
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
                <div class="row x_title">
                    <div class="col-md-6">
                    </div>
                    <div class="col-md-6 text-right">
                        @can('Create Template')
                            <button class="btn btn-primary" data-toggle="modal" data-target="#create_template_modal">
                                New Message Template
                            </button>

                        @endcan
                    </div>
                </div>
                <div class="x_content">
                    <table class="table table-striped table-sm  no-margin">
                        <thead>
                        <tr>
                            <th>Id</th>
                            <th>Template Title</th>
                            <th>Message Template</th>
                            <th>Created By</th>
                            <th>Reviewed By</th>
                            <th>Status</th>
                            <th>Created at</th>
                            <th></th>
                            <th>Action</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($templates as $template)
                            <tr>
                                <td>{{ $template->id }}</td>
                                <td><a href="{{ route('templates.show', $template->id) }}">{{ $template->title }}</a></td>
                                <td>{{ $template->template }}</td>
                                <td>
                                    <a href="{{ route('users.show', $template->created_by) }}">{{  $template->creator->name }}</a>
                                </td>
                                <td>
                                    @if(!is_null($template->reviewed_by))
                                        <a href="{{ route('users.show', $template->reviewed_by) }}">{{ $template->reviewer->name }}</a>
                                    @endif
                                </td>
                                <td>{{ $template->status }}</td>
                                <td>{{ $template->created_at }}</td>
                                <td>
                                    @if($template->status == 'PENDING')
                                        @can('Action on template request')
                                            <a href="{{ route('template.action', [$template->id,'approve']) }}"
                                               class="btn btn-primary btn-xs">Approve</a>
                                            <a href="{{ route('template.action', [$template->id,'decline']) }}"
                                               class="btn btn-danger btn-xs">Decline</a>
                                        @endcan
                                    @endif
                                </td>
                                <td>
                                    @can('Delete Template')
                                        {{ Form::model($template,['url' => '/templates/'.$template->id,'method' => 'DELETE']) }}
                                        <input type="hidden" name="id" value="{{ $template->id}}"/>
                                        <button type="submit"
                                                class="btn {{$template->trashed() ? 'btn-info':'btn-danger'}}  btn-xs"> {{$template->trashed() ? 'Restore':'Delete'}}</button>
                                        {{ Form::close() }}
                                    @endcan
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                    {{ $templates->links() }}
                </div>
            </div>
        </div>
    </div>
@stop

@section('modals')
    @can('Create Template')
        <div class="modal fade bs-example-modal-lg" id="create_template_modal" tabindex="-1" role="dialog" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">

                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal"><span
                                aria-hidden="true">×</span>
                        </button>
                        <h4 class="modal-title" id="myModalLabel">New Message Template</h4>
                    </div>
                    <form method="POST" action="{{ route("templates.store") }}" enctype="multipart/form-data">
                        {{csrf_field()}}
                        <div class="modal-body">
                            <div class="form-group">
                                <label>Template Title<span class="required">*</span></label>
                                <input class="form-control" name="title"
                                          placeholder="Template Title">{{ old('title') }}</input>
                            </div>
                            <div class="form-group">
                                <label>SMS Template<span class="required">*</span></label>
                                <textarea class="form-control" name="template"
                                          placeholder="Message Template">{{ old('template') }}</textarea>
                            </div>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                            <button type="submit" class="btn btn-primary">Save Template</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    @endcan
@stop

resources/views/templates/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <h2>{{ $template->tile }}
                        <small>Template details</small>
                    </h2>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">
                    <div class="col-md-3 col-sm-3 col-xs-12 profile_left">
                        <h3>{{ $template->title }}</h3>
                        <ul class="list-unstyled user_data">
                            <li><i class="fa fa-question-circle user-profile-icon"></i>
                                {{ $template->status }}
                            </li>
                        </ul>
                        @can("Edit Template")
                            <a class="btn btn-success" data-toggle="modal" data-target=".bs-example-modal-lg"><i
                                    class="fa fa-edit m-right-xs"></i>Edit Template</a>
                        @endif
                        <br/>
                    </div>
                    <div class="col-md-9 col-sm-9 col-xs-12">
                        <div class="" role="tabpanel" data-example-id="togglable-tabs">
                            <ul id="myTab" class="nav nav-tabs bar_tabs" role="tablist">
                                <li role="presentation" class="active">
                                    <a href="#tab_content1" id="home-tab" role="tab" data-toggle="tab"
                                       aria-expanded="true">Template Details</a>
                                </li>
                            </ul>
                            <div id="myTabContent" class="tab-content">
                                <div role="tabpanel" class="tab-pane fade active in" id="tab_content1"
                                     aria-labelledby="home-tab">
                                    <table class="table table-striped table-sm no-margin">
                                        <thead>
                                        <tr>
                                            <th>Id</th>
                                            <th>Template Title</th>
                                            <th>Message Template</th>
                                            <th>Status</th>
                                            <th>Created By</th>
                                            <th>Reviewed By</th>
                                            <th>Created at</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                            <tr>
                                                <td>{{ $template->id  }}</td>
                                                <td>{{ $template->title  }}</td>
                                                <td>{{ $template->template  }}</td>
                                                <td>{{ $template->status  }}</td>
                                                <td>{{ $template->creator->name }}</td>
                                                <td>{{ $template->reviewer ? $template->reviewer->name : '' }}</td>
                                                <td>{{ $template->created_at  }}</td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@stop

@section('modals')
    @can('Edit Template')
        <div class="modal fade bs-example-modal-lg" tabindex="-1" role="dialog" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span>
                        </button>
                        <h4 class="modal-title" id="myModalLabel">Edit {{ $template->title }}</h4>
                    </div>
                    {{ Form::model($template,['route' => ['templates.update', $template->id],'method' => 'put']) }}

                    <div class="modal-body">
                        <div class="form-group">
                            <label>Template Title<span class="required">*</span></label>
                            {{  Form::text('title', $value = $template->title, $attributes =[
                            'class' => 'form-control'
                            ]) }}
                        </div>
                        <div class="form-group">
                            <label>Template Body<span class="required">*</span></label>
                            {{  Form::textarea('template', $value = $template->template, $attributes =[
                            'class' => 'form-control'
                            ]) }}
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-primary">Update Template</button>
                    </div>
                    {{ Form::close() }}
                </div>
            </div>
        </div>
    @endcan
@stop

@section('styles')
    <link href="{{ asset('vendors/bootstrap-daterangepicker/daterangepicker.css') }}" rel="stylesheet">
@stop
@section('scripts')
    <script src="{{ asset('/vendors/raphael/raphael.min.js') }}"></script>
    <script src="{{ asset('/vendors/morris.js/morris.min.js') }}"></script>
    <!-- bootstrap-progressbar -->
    <script src="{{ asset('/vendors/bootstrap-progressbar/bootstrap-progressbar.min.js') }}"></script>
    <!-- bootstrap-daterangepicker -->
    <script src="{{ asset('/vendors/moment/min/moment.min.js') }}"></script>
    <script src="{{ '/vendors/bootstrap-daterangepicker/daterangepicker.js' }}"></script>

@stop

resources/views/templates/upload_messages.blade.php
@extends('layouts.app')

@section('scripts')
    <script>
        $(document).ready(function () {
            $(".delete-template").on('click', function () {
                var r = confirm("Are you sure you want to delete this message template?");
                if (r) {
                    $.ajax({
                        url: '{{ url('templates') }}/' + $(this).attr('id'),
                        type: 'DELETE',  // user.destroy
                        success: function (result) {
                            console.log(result);
                            location.reload();
                        },
                        fail: function (error) {
                            console.log(error);
                            alert("Error deleting template");
                        }
                    });
                }
            });
        });
    </script>
@endsection
@section('actions')
    <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
        <form method="get">
            <div class="input-group">
                <input type="text" name="search" value="{{ isset($_GET['search']) ? Request::get('search') :'' }}"
                       class="form-control"
                       placeholder="Search for...">
                <span class="input-group-btn"><button class="btn btn-default" type="submit">Search</button></span>
            </div>
        </form>
    </div>
@endsection
@section('content')
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
                <div class="row x_title">
                    <div class="col-md-6">
                    </div>
                    <div class="col-md-6 text-right">
                        @if($templateUpload->status == 'PENDING')
                            @can('Create Template')
                                <a href="{{ route('template_uploads.approve', $templateUpload->id) }}" class="btn btn-primary">
                                   Approve & Send
                                </a>
                            @endcan

                        @else
                            <a href="{{ route('template_uploads.report', $templateUpload->id) }}" class="btn btn-primary">
                                Download Report
                            </a>
                        @endif
                    </div>
                </div>
                <div class="x_content">
                    <table class="table table-striped table-sm  no-margin">
                        <thead>
                        <tr>
                            <th>Id</th>
                            <th>Phone Number</th>
                            <th>Message</th>
                            <th>Units</th>
                            <th>Status</th>
                            <th>Sent At</th>
                            <th>Submit Date</th>
                            <th>Done Date</th>
                            <th>Delivery Status</th>
                            <th>Action</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($messages as $template)
                            <tr>
                                <td>{{ $template->id }}</td>
                                <td>{{ $template->phone_number }}</td>
                                <td>{{ $template->message }}</td>
                                <td>{{ $template->units }}</td>
                                @if(!is_null($template->sentMessage))
                                    <td>{{$template->sentMessage->status}}</td>
                                    <td>{{$template->sentMessage->processed_at}}</td>
                                    <td>{{$template->sentMessage->submit_date}}</td>
                                    <td>{{$template->sentMessage->done_date}}</td>
                                    <td>{{$template->sentMessage->delivery_status}}</td>
                                    <td></td>
                                @else
                                    <td>{{ $template->status }}</td>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                @endif
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                    {{ $messages->links() }}
                </div>
            </div>
        </div>
    </div>
@stop

resources/views/templates/uploads.blade.php
@extends('layouts.app')

@section('scripts')
    <script>
        $(document).ready(function () {
            $(".delete-template").on('click', function () {
                var r = confirm("Are you sure you want to delete this message template?");
                if (r) {
                    $.ajax({
                        url: '{{ url('templates') }}/' + $(this).attr('id'),
                        type: 'DELETE',  // user.destroy
                        success: function (result) {
                            console.log(result);
                            location.reload();
                        },
                        fail: function (error) {
                            console.log(error);
                            alert("Error deleting template");
                        }
                    });
                }
            });
        });
    </script>
@endsection
@section('actions')
    <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
        <form method="get">
            <div class="input-group">
                <input type="text" name="search" value="{{ isset($_GET['search']) ? Request::get('search') :'' }}"
                       class="form-control"
                       placeholder="Search for...">
                <span class="input-group-btn"><button class="btn btn-default" type="submit">Search</button></span>
            </div>
        </form>
    </div>
@endsection
@section('content')
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
                <div class="row x_title">
                    <div class="col-md-6">
                    </div>
                    <div class="col-md-6 text-right">

                        @can('Create blast messages')
                            <button class="btn btn-primary" data-toggle="modal" data-target=".template-modal">
                                New Message with Template
                            </button>
                        @endcan
                    </div>
                </div>
                <div class="x_content">
                    <table class="table table-striped table-sm  no-margin">
                        <thead>
                        <tr>
                            <th>Id</th>
                            <th>Template</th>
                            <th>Sender</th>
                            <th>Message</th>
                            <th>Units</th>
                            <th>Recipients</th>
                            <th>Created By</th>
                            <th>Status</th>
                            <th>Created at</th>
                            <th>Action</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($uploads as $template)
                            <tr>
                                <td>{{ $template->id }}</td>
                                <td>
                                    <a href="{{ route('templates.show', $template->template->id) }}">{{ $template->template->title }}</a>
                                </td>
                                <td>{{ $template->sender_id }}</td>
                                <td>{{ $template->template->template }}</td>
                                <td>{{ $template->messages->sum('units') }}</td>
                                <td>{{ $template->messages->count() }}</td>
                                <td>
                                    <a href="{{ route('users.show', $template->uploaded_by) }}">{{  $template->uploadedBy->name }}</a>
                                </td>
                                <td>{{ $template->status }}</td>
                                <td>{{ $template->created_at }}</td>
                                <td>
                                    <a href="{{ route('templates_uploads.show', [$template->id]) }}"
                                       class="btn btn-primary btn-xs">View</a>
                                    @if($template->status == 'PENDING')
                                        @can('Delete Template')
                                            {{ Form::model($template,['url' => '/templates_uploads/'.$template->id,'method' => 'DELETE']) }}
                                            <input type="hidden" name="id" value="{{ $template->id}}"/>
                                            <button type="submit"
                                                    class="btn {{$template->trashed() ? 'btn-info':'btn-danger'}}  btn-xs"> {{$template->trashed() ? 'Restore':'Delete'}}</button>
                                            {{ Form::close() }}
                                        @endcan
                                    @endif
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                    {{ $uploads->links() }}
                </div>
            </div>
        </div>
    </div>
@stop


@section('modals')
    @can('Create blast messages')
        <div class="modal fade bs-example-modal-lg template-modal" tabindex="-1" role="dialog" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">

                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal"><span
                                aria-hidden="true">×</span>
                        </button>
                        <h4 class="modal-title" id="myModalLabel">Schedule messages</h4>
                    </div>
                    <form method="POST" action="{{ route("blast.template") }}" enctype="multipart/form-data">
                        {{csrf_field()}}
                        <div class="modal-body">
                            <div class="form-group">
                                <label>Short code</label>
                                <select class="form-control" id="short_code" name="short_code" required>
                                    <option>Select short code</option>
                                    @foreach($shortCodes as $shortCode)
                                        <option value="{{ $shortCode->id }}">{{ $shortCode->short_code }}</option>
                                    @endforeach
                                </select>
                            </div>
                            <div class="form-group">
                                <label>SMS Template</label>
                                <select class="form-control" id="template" name="template">
                                    <option disabled selected>Select Template</option>
                                    @foreach($templates as $template)
                                        <option value="{{ $template->id }}">{{ $template->title }}</option>
                                    @endforeach
                                </select>
                            </div>
                            <div class="form-group">
                                <label>Template Variables (.csv containing Phone Number and each template variable {VAR} as  header) <span class="required">*</span></label>
                                <input type="file" name="template_variables" class="form-control"/>
                            </div>
                            <div class="form-group">
                                <label>Schedule time</label>
                                <input type="datetime-local" value="{{ old('schedule_time') }}"
                                       name="schedule_time" class="form-control"/>
                            </div>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                            <button type="submit" class="btn btn-primary">Schedule Blast</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    @endcan
@stop